# Generated by Django 4.0.4 on 2022-07-24 15:45

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_list_id', models.CharField(max_length=120)),
                ('_created_at', models.DateTimeField()),
                ('_last_updated', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(default='test', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('query', django.db.models.manager.Manager()),
            ],
        ),
    ]
