# Generated by Django 4.0.4 on 2022-07-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qbwc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
            ],
        ),
    ]
