# Generated by Django 4.0.4 on 2022-07-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbwc', '0002_alter_customer_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='_batch_id',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='_batch_status',
            field=models.CharField(choices=[('BATCHED', 'BATCHED'), ('UN_BATCHED', 'UN_BATCHED')], default='UN_BATCHED', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='_list_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
