# Generated by Django 4.0.4 on 2022-07-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccount',
            name='file_path',
            field=models.FilePathField(default='c:/'),
            preserve_default=False,
        ),
    ]
