# Generated by Django 4.0.4 on 2022-05-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccount',
            name='password',
            field=models.CharField(default='test', max_length=30),
        ),
    ]
