# Generated by Django 4.0.4 on 2022-05-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_books', '0002_serviceaccount_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Created'), ('5', 'Approved'), ('2', 'Running'), ('6', 'Error'), ('3', 'Failed'), ('4', 'Success')], max_length=15)),
                ('ticket', models.CharField(max_length=120)),
                ('object_type', models.CharField(blank=True, max_length=20, null=True)),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
