# Generated by Django 4.0.4 on 2022-07-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_books', '0002_serviceaccount_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceaccount',
            name='file_path',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
