# Generated by Django 4.0.4 on 2022-05-25 04:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_books', '0003_ticketqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketqueue',
            name='ticket',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
