# Generated by Django 4.0.4 on 2022-07-24 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_books', '0003_alter_serviceaccount_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketqueue',
            name='resolved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketqueue',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketqueue',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PATCH', 'PATCH')], default='GET', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticketqueue',
            name='model',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='ticketqueue',
            name='status',
            field=models.CharField(choices=[('1', 'Created'), ('2', 'Approved'), ('3', 'Processing'), ('4', 'Success'), ('5', 'Error'), ('6', 'Failed')], default='1', max_length=5),
        ),
    ]
