# Generated by Django 4.0.4 on 2022-07-24 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_books', '0004_serviceaccount_is_active_ticketqueue_resolved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketqueue',
            name='ticket',
            field=models.CharField(default=uuid.uuid4, max_length=123),
        ),
    ]
