# Generated by Django 4.0.4 on 2022-07-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_books', '0005_alter_ticketqueue_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketqueue',
            name='ticket',
        ),
    ]
