# Generated by Django 4.0.4 on 2022-07-24 18:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_books', '0006_remove_ticketqueue_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketqueue',
            name='ticket',
            field=models.CharField(default=uuid.uuid4, max_length=123),
        ),
    ]
