# Generated by Django 4.0.4 on 2022-07-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_books', '0007_ticketqueue_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketqueue',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PATCH', 'PATCH')], default='GET', max_length=5),
        ),
    ]
