# Generated by Django 4.0.4 on 2022-09-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_books', '0008_alter_ticketqueue_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccount',
            name='config',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
