# Generated by Django 4.0.4 on 2022-09-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_books', '0009_serviceaccount_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceaccount',
            name='config',
            field=models.TextField(blank=True, null=True),
        ),
    ]
