# Generated by Django 4.0.4 on 2022-09-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_books', '0010_alter_serviceaccount_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccount',
            name='app_url',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
